version: '3.8'

services:
  web1:
    build: .
    container_name: web1
    networks:
      - prod-net

  web2:
    build: .
    container_name: web2
    networks:
      - prod-net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes: -./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: -80:80
    depends_on:
      - web1
      - web2
    networks:
      - prod-net

networks:
  prod-net:
    driver: bridge
